on:
  workflow_dispatch:
    branches:
      - main

jobs:
  infrastructure:
    name: 'infrastructure'
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v2
    
        - name: install npm
          uses: actions/setup-node@v3
          with:
            node-version: 14.x
        
        - name: Initialize Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.2.4
        
        - name: Configure AWS CLI
          run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
            aws configure set default.region ${{ vars.AWS_REGION }}

        - name: terraform init -migrate-state
          id: InitMigrateState
          run: terraform init -reconfigure

        - name: Terraform Init
          id: Init
          run: terraform init
    
        - name: Terraform Validate
          id: Validate
          run: terraform validate
    
        - name: Terraform Plan
          id: Plan
          run: |
            export profile=$AWS_PROFILE
            export region=$AWS_REGION$
            export s3_bucket=$BUCKET_NAME

            terraform plan
          env:
            profile: ${{secrets.AWS_PROFILE}}
            region: ${{secrets.AWS_REGION}}
            s3_bucket: ${{secrets.BUCKET_NAME}}

        - name: Terraform Apply
          id: Apply
          run: |
            export profile=$AWS_PROFILE
            export region=$AWS_REGION$
            export s3_bucket=$BUCKET_NAME

            terraform apply -auto-approve
          env:
            profile: ${{secrets.AWS_PROFILE}}
            region: ${{secrets.AWS_REGION}}
            s3_bucket: ${{secrets.BUCKET_NAME}}